### ISSUE TITLE
Minimum File Size feature

### ISSUE THREAD

**Issue by equity69** [fyneworks/multifile#10]
I have been using this plugin for a couple years, and it has been great! ... this is not something i would call an issue as much as a request. i have need of a means of checking to make sure that an image being uploaded is at least a minimum size ;) ... i know there is validation for maximum size, and i was wondering if there was a means of validating a min-size? thank you!

**Comment by fyneworks** [comment]
Good idea... see 4067ab4648ac253300b78f5adce53420b487fcdc (branch validation-min)
