### ISSUE TITLE
How to add files programmatically

### ISSUE THREAD

**Issue by MinionAttack** [fyneworks/multifile#100]
Hi, 

I am trying to implement a copy and paste functionality but even after reviewing the code I am not able to do it. I can assign the files but the plugin does not show the list of files with the option to delete them.

Is it possible to do this or the plugin doesn't allow it at the moment?

Best regards.

**Comment by fyneworks** [comment]
Copy paste functionality is beyond the scope of this plugin (all this plugin does is create new file inputs).

Try somrthing like https://gist.github.com/STRd6/5286415 - you'll need to...
* handle paste events
* detect mime-types
* read base64 data https://developer.mozilla.org/en-US/docs/Web/API/FileReader
* upload it directly
...or somerthing to that effect.
