### ISSUE TITLE
"accept" not compatible with mime types

### ISSUE THREAD

**Issue by mick88** [fyneworks/multifile#101]
I have setup the multifile input with `accept="image/*"`. This way google chrome filters files in the file picker dialog down to just image files.

However, after applying this multifile plugin, I am getting an error "jpg file is not allowed, please try again". jpg is notably an image file.

I see that the library has its own format for what "accept" should look like that does not agree with Google Chrome. When I set `accept="jpg|png"`, google chrome no longer filters files in the file picker popup.

My field code:
```html
<input type="file" name="test_multifileclearableinput" class="multi MultiFile-applied" accept="image/*" capture="camera" title=" " id="id_test_multifileclearableinput" multiple="multiple" value="">
```

**Comment by fyneworks** [comment]
The plugin's behaviour is not modeled on the browser's behaviour and it does not accept wildcards. It's a regular expression.
https://github.com/fyneworks/multifile/blob/01107722a8a78549ea2dfedec47f924b2750ba73/jquery.MultiFile.js#L183

You can try using ```data-accept="jpg|png"``` instead, and it cannot be a wildcard. You must set a list of the specific individual extensions you accept like "jpb|png".

**Comment by mick88** [comment]
Is is possible to disable file extension validation? I already have backend and browser validation and this would be the 3rd place where I have to list out all supported file types, and sometimes I need to be able to just accept *any* file.

**Comment by fyneworks** [comment]
I don't actively support this project any more. I would recommend forking and using a modified version in your project. 

The plugin picks up the ```MultiFile.E.attr('accept')``` attribute on like 112.
https://github.com/fyneworks/multifile/blob/01107722a8a78549ea2dfedec47f924b2750ba73/jquery.MultiFile.js#L112

Remove this line and the plugin will not use the value of the accept attribute.

This would be a breaking change for anyone who is using it as it is right now so we shouldn't merge this change here.

**Comment by fyneworks** [comment]
Actually, I had an idea to ignore the attribute without creating a breaking chage. Can you confirm if the proposed version works? 
https://github.com/fyneworks/multifile/pull/102/commits/6939ae7ca8310a7df36095df1c946caba9785449

**Comment by mick88** [comment]
Yes, this does work, thank you!

it ignores my "accept" attribute when set to "image/*" but still respects file extensions "jpg|gif"

**Comment by fyneworks** [comment]
Alright,  done.
![#yolo](https://media.giphy.com/media/9xnNG7EN2h822ithtT/giphy.gif)
