### ISSUE TITLE
Cloned inputs are displayed when there is a very large vertical scroll

### ISSUE THREAD

**Issue by MinionAttack** [fyneworks/multifile#106]
Hi,

Using the plugin I have seen a problem when there is a list that produces a very large vertical scroll.

The problem is here: [Block of code](https://github.com/fyneworks/multifile/blob/master/jquery.MultiFile.js#L417)

```
// Hide this element (NB: display:none is evil!)
$(this).css({
position: 'absolute',
top: '-3000px'
});
```

If the vertical scroll is equal to or greater than _3000px_, when scrolling up, the cloned inputs are seen floating on the screen.

Is it possible to change the value to a higher value or could the plugin code be modified to allow defining the number of pixels parametrically?

Regards.

**Comment by digggggggggg** [comment]
But the absolute positioning should put the element at the top of the screen anyway, the size of the vertical scroll shouldn't matter.

Can you check if there are any conflicting rules? Or can you set up an example?

We could make the value -9999999 or whatever but that feels even dirtier and hackier than this old thing already is.

**Comment by MinionAttack** [comment]
Hi, when I get back from the Christmas break I can check to see if there are any conflicting rules with the styles that cause this. Right now I have applied a higher number, but as you say it's not the best way.

Is it possible that if you use fragments, as you do with Thymeleaf for example, it could affect the absolute not working correctly?

Best regards.

**Comment by MinionAttack** [comment]
Hi,

I checked and we don't have any CSS that overrides the styling of the input element:

![Input](https://user-images.githubusercontent.com/10078549/211273505-2a4e3c9d-60b8-4e1f-a910-cf7a3f437e13.png)

The input is displayed if the vertical scroll is equal to or greater than 3000 pixels:

![Proof](https://user-images.githubusercontent.com/10078549/211273892-dbb6a552-bbb6-4abe-a403-6ea302cfef0e.PNG)

Best regards.
