### ISSUE TITLE
Backbone + MultiFile

### ISSUE THREAD

**Issue by jm90m** [fyneworks/multifile#11]
Lots of random issues with MultiFile + Backbone Views, more specifically MultiFile is unable to append the list of files to the element in the current view. Will try to fork this project and add a fix to this myself.

**Comment by fyneworks** [comment]
Any news on this? Have not used Backbone before but I may have some time to help debug in the next couple of weeks.

**Comment by jm90m** [comment]
Sorry haven't checked this in a while, but I was able to get it to work with my Backbone App. I'll post what I did when I get back from Vacation!

**Comment by fyneworks** [comment]
Closing for now unless somebody thinks it should remain open. Glad you got it to work. Do share your solution if you have a chance... :-)
