### ISSUE TITLE
Disable duplicate checking

### ISSUE THREAD

**Issue by JurakZdenek** [fyneworks/multifile#111]
Is it possible to disable the duplicate name check? Because when I use the camera to attach a file on iOS, each file is named image.jpeg and the library won't let me upload multiple files. How to bypass it? Thank you

**Comment by fyneworks** [comment]
You're welcome to fork and remove the code block starting on line 326 https://github.com/fyneworks/multifile/blob/master/jquery.MultiFile.js#L326

That may cause undesigned behaviour. The file input is a special type of input, the value of the input cannot be modified, the plugin cannot control the name of the file being uploaded.

If you want complete freedom you need to use the [FileReader api](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) to load all information about the files, including their data, then you can do anything you like, including renaming files with the same name, or just ignoring the names entirely.
