### ISSUE TITLE
How to display the Remove link after the filename

### ISSUE THREAD

**Issue by tim3673** [fyneworks/multifile#12]
I'd like to display the filename on the left, and the remove icon on the right. I've set a custom remove icon using the Remove string, and I've set a custom file string (including an icon) with the File string. But the remove icon shows to the left of the filename, I'd like to have it displayed on the right.

Is this possible?

**Comment by fyneworks** [comment]
You could use css to float it right....
`.MultiFile-remove{ float:right; }`
