### ISSUE TITLE
How to Remove alert validation in JQuery Multifile

### ISSUE THREAD

**Issue by RamDeveloper** [fyneworks/multifile#13]
I am using jquery multifile upload plugin http://www.fyneworks.com/jquery/multifile can able to select document but when i tried to select wrong file it shows validation message as alert

 "   You cannot select a .mp4 file. Try again...  "

instead of alert message how to show as validation text message ? also any possiblities to add "Required" validation for file using this plugin.

**Comment by fyneworks** [comment]
You can override the default error function with your own function like this...
`
$(...).MultiFile({
  error: function(error_string){
    console.error('an error happened:' + error_string);
  }
})
`

and you can disable it completely like this:
`
$(...).MultiFile({
  error: false
})
`
