### ISSUE TITLE
Remove button for each file

### ISSUE THREAD

**Issue by PatelUtkarsh** [fyneworks/multifile#17]
Currently there is no remove button for each file, 

If i select 3 files all 3 files are bundled with single cross arrow which should not be the case.

**Comment by digggggggggg** [comment]
When you select multiple files they cannot be removed individually.

**Comment by PatelUtkarsh** [comment]
are you sure it can not be removed ?

**Comment by digggggggggg** [comment]
The file input is read only. If you select several files at once (as a
group) they can only be removed together, as one. The array can not be
changed. Absolutely sure (according to current documentation).

**Comment by PatelUtkarsh** [comment]
Okay Thank you!
