### ISSUE TITLE
Multilingual support doesn't seem to work

### ISSUE THREAD

**Issue by btsvennes** [fyneworks/multifile#21]
Hi!
Thank you for a great plugin. It works very well, except for the multilingual support and file list customization (both using the STRING property). I get the same behavior in your examples. Is there something wrong with my setup?

Tested on IE11 and Firefox ver37.

Regards
Bjørn Terje Svennes

**Comment by btsvennes** [comment]
It seems to be something strange on line 148 in jquery.MultiFile.js. As far as I can understand the call MultiFile.STRING = $.extend(MultiFile.STRING || {}, $.fn.MultiFile.options.STRING, MultiFile.STRING); will overwrite the STRING option set by the preceeding call to $.extend(MultiFile, o || {}); (on line 147). I tried a quick fix by replacing line 148 with $.extend(MultiFile.STRING || {}, o.String ||$.fn.MultiFile.options.STRING, MultiFile.STRING); This is not a good solution since missing strings in o.STRING will not get their default values. Can the problem be related to changes in the extend-method in JQuery since I assume that this has been working at some stage?

**Comment by btsvennes** [comment]
This works (replacement for line 148): MultiFile.STRING = $.extend({}, $.fn.MultiFile.options.STRING, MultiFile.STRING);

**Comment by fyneworks** [comment]
Hi guys, sorry for being away for so long. One of our users has kindly shared a fix for this which we've merged into the repo.

**Comment by fyneworks** [comment]
@btsvennes that's exactly what he did too. Haven't been around for a while, sorry I didn't spot your contribution here!
