### ISSUE TITLE
Changing the file name

### ISSUE THREAD

**Issue by cesaralbuquerque** [fyneworks/multifile#22]
Hello.
I'm trying to change the name of the file uploaded.
I have changed the code in jquery.Multifile.js on the line 169 to always setting the file name to "something.jpg", but didn't work.
Anybody can help me?

Here is the code:
```javascript
166   // set file name
167   file.name = " something.jpg";
168   // execute function in element's context, so 'this' variable is current element
169   rv = handler.apply(MultiFile.wrapper, [element, file.name, MultiFile, file]);
```

**Comment by digggggggggg** [comment]
You can't.
You have to upload the file then rename it on the server.
And you can't set the value on the client either. The <input type="file"/> element is read only.

**Comment by cesaralbuquerque** [comment]
thanks for your anwser.
the problem is: i have two inputs image  with multi file thats i send this files on only one form.
I need to discriminate the file on the fist input to know on server side who is the fist file.

Do you have some ideia?

**Comment by digggggggggg** [comment]
If you have 2 inputs can't you gave them different names and then upload one, rename it, then upload the other and renamed that?

If you only have 1 <input/> element the files are submitted in the order the user/browser picks them, you cannot re-order it or rename them in any way... read only. no way around it.

**Comment by cesaralbuquerque** [comment]
the only way i found is: on the list of pictures, the user must select what picture that will be the icon and which will be the wallpaper.

This's the case:

![capturar](https://cloud.githubusercontent.com/assets/7987784/7282413/3750bd6c-e906-11e4-9fba-dad53e5918c8.JPG)


thanks Diego and thanks everyone

**Comment by fyneworks** [comment]
That looks perfect. Thanks for sharing this as I'm sure it will help others!
