### ISSUE TITLE
Formatting of list of several files added together

### ISSUE THREAD

**Issue by ugoertz** [fyneworks/multifile#26]
Hi,

thanks for your work, it is very useful.

If I am not mistaken, [line 488](https://github.com/fyneworks/multifile/blob/master/jquery.MultiFile.js#L488) in jquery.MultiFile.js should be

```javascript
if(i>0) names.append(', ');
```
(rather than `i>1`). As it is now, between the first and second entries there is no comma, if multiple files are selected together.

Ulrich

**Comment by Micteu** [comment]
Well, shucks. I did a pull request to fix this yesterday. If I had known the issue was sitting with a solution for nine months without the owners fixing it, I wouldn't have bothered. It looks like Fyneworks doesn't support this product anymore.

**Comment by fyneworks** [comment]
@Micteu - fair. And I'm sorry. I've been busy but I will make time.

Let's continue this discussion over on https://github.com/fyneworks/multifile/pull/35
