### ISSUE TITLE
Adding a File

### ISSUE THREAD

**Issue by praveenkumargurrala** [fyneworks/multifile#27]
Hi

I am using MultiFile Js For Multiple File Upload.
> First I have added 3 files using file control 
1. one.txt
2. two.txt
3. three.txt
and stored in Database 

> Now I want to update the Files
In this option i am retrieving the binary data and file name from database.
How to append this stream data files to file control using Multifile js
So that i can remove one or more files
Also i can add some more files to it
After all i will save to Database.

It is possible or not??

Please help me in this

Thanks & Regards
Praveen

**Comment by fyneworks** [comment]
That's far beyond the scope of this plugin. You'll need some server-side code to retrieve and manage the data in your database. This is a client-side file selection plugin only. It never sees and cannt manage the contents of the file or the stuff you store in your database.
