### ISSUE TITLE
Check Filesize BUG

### ISSUE THREAD

**Issue by robertyao** [fyneworks/multifile#3]
Dear Frind,
       I was look for a upload tool that can mulit post and check the filesizs before
post to the server.
       When test with your demo! Everything is ok but a bug  at "Validating Sizes"  .
       Here is the step i do:
       step 1:choose a file (less than 1M)
       step 2:remove it
       step 3:choose another file(less than 1M)
       and then error occored Message "The File selected exceed the maximum size                  permited(1.3Mb>1024Kb)"

**Comment by fyneworks** [comment]
Sorry for not spotting this before guys, and apologies for taking so long to work on the plugin. This should be working now. See 0b5580294e354bd70142d80a3bca98fc56d82359
