### ISSUE TITLE
multiple forced on input if max > 1

### ISSUE THREAD

**Issue by kila03** [fyneworks/multifile#30]
Because of this code

    if(o.max>1) MultiFile.E.attr('multiple','multiple').prop('multiple',true);

multiple-attribute is forced on input even if I am not interested in selecting more than one file at a time but still wants to enable uploading multiple files. My best guess would be to remove the line and let users manually put multiple on input-field if needed.

**Comment by fyneworks** [comment]
See https://github.com/fyneworks/multifile/pull/24
