### ISSUE TITLE
How to add checkboxes before each of images?

### ISSUE THREAD

**Issue by thanhoangxuannghiep** [fyneworks/multifile#34]
I use this plugin but when I choose file and click ok. All file was moved to div "file_list" which I created. However, Only a checkbox for all files, so, how can I add a checkbox before each of images? Thank you.

**Comment by fyneworks** [comment]
Take a look at example 8B on the documentation,
http://www.fyneworks.com/jquery/multiple-file-upload/
Under Examples > Expert Examples.

You need to use the STRING option, like this:
```
$('#your-element-id').MultiFile({
	STRING:{
		file: '<input value="$file" type="checkbox"/> $file'
	}
})
```
