### ISSUE TITLE
No indication that this product is no longer supported by fyneworks.

### ISSUE THREAD

**Issue by Micteu** [fyneworks/multifile#36]
Could something be put in the Readme (and preferably on the [website](http://www.fyneworks.com/jquery/multifile)) showing that the author is no longer supporting this? It looks like no issues have been addressed or pull requests accepted for a long time. Even [www.fyneworks.com](http://www.fyneworks.com) indicates they don't do jQuery plugins anymore.

**Comment by fyneworks** [comment]
Good shout @Micteu. My bad. I've been super busy and not had much time, but I will go through all the outstanding issues and pull requests now.

**Comment by Micteu** [comment]
Oh, hello. Glad you're still active.
