### ISSUE TITLE
populate the object

### ISSUE THREAD

**Issue by duku602** [fyneworks/multifile#40]
Hello,

I am trying to use the script when I am editing an article and I can't figure how to populate the list with my existing images. 
Can I send an array to the object in order to populate the list? (if yes, how?)

I am trying to get something similar with the picture attached when I edit an article.
[http://i.imgur.com/WaytyPG.jpg](http://i.imgur.com/WaytyPG.jpg)

**Comment by fyneworks** [comment]
That won't be anything to do with the plugin. You can't set the value of the file input element. If you have files in your project you'll need some server side language to produce a list with some controls yo manipulate them (rename, delete, etc). But that's just not within the scope of this plugin.

**Comment by duku602** [comment]
Oh.. OK, I thought the list with existing images had to be sent through the plugin.
I can easily write the php to populate the list.

Thank you for your help and keep up de GOOD work! :+1:

**Comment by fyneworks** [comment]
👍

**Comment by cariquitanmac** [comment]
Do you have any workaround for this? I know this is a security issue but we badly need it  sometimes :+1:
