### ISSUE TITLE
Issue with fileupload list 

### ISSUE THREAD

**Issue by Ananthan209** [fyneworks/multifile#43]
Hi all,
 im new to the github..i want one help in my project . i need to delete each file which is seleceted while uploading.now i can delete all files in single click but i want to delete each and every file individually.
this file is part of the  jquery.multifile.js.
thanks....

MultiFile.addToList = function (slave, slave_count, files) {
					//if(window.console) console.log('MultiFile.addToList',slave_count);

					//# Trigger Event! onFileAppend
					MultiFile.trigger('FileAppend', slave, MultiFile, files);
					//# End Event!
					
					var names = $('<span/>');
					$.each(files, function (i, file) {
						var v = String(file.name || '' ),
								S = MultiFile.STRING,
								n = S.label || S.file || S.name,
								t = S.title || S.tooltip || S.selected,
								p = '<img class="MultiFile-preview" style="'+ MultiFile.previewCss+' display:none;"/>',
								label =	$(
										(
											'<span class="MultiFile-label" title="' + t + '">'+
												'<span class="MultiFile-title">'+ n +'</span>'+
												(MultiFile.preview || $(slave).is('.with-preview') ? p : '' )+
											'</span>'
										)
										.replace(/\$(file|name)/gi, (v.match(/[^\/\\]+$/gi)||[v])[0])
										.replace(/\$(ext|extension|type)/gi, (v.match(/[^\.]+$/gi)||[''])[0])
										.replace(/\$(size)/gi, sl(file.size || 0))
										.replace(/\$(preview)/gi, p)
								);
						
						// now supports preview. Just add an image with class preview to the "file" string
						label.find('img.MultiFile-preview').each(function(){
							var t = this;
							var oFReader = new FileReader();
							oFReader.readAsDataURL(file);
							oFReader.onload = function (oFREvent) {
								t.src = oFREvent.target.result;
							};
						});

						// append file label to list
						if(i>1) names.append(', ');
						names.append(label);

					});

					//$.each(files, function (i, file) {
						// Create label elements
						var
							r = $('<div class="MultiFile-label"></div>'),
							b = $('<a class="MultiFile-remove" href="#' + MultiFile.wrapID + '">' + MultiFile.STRING.remove + '</a>')
								.click(function () {

									//# Trigger Event! onFileRemove
									MultiFile.trigger('FileRemove', slave, MultiFile, files);
									//# End Event!

									MultiFile.n--;
									MultiFile.current.disabled = false;

									// Remove element, remove label, point to current
									MultiFile.slaves[slave_count] = null;
									$(slave).remove();
									$(this).parent().remove();

									// Show most current element again (move into view) and clear selection
									$(MultiFile.current).css({
										position: '',
										top: ''
									});
									$(MultiFile.current).reset().val('').attr('value', '')[0].value = '';

									// rebuild array with the files that are left.
									var newfs = [];
									for (var x in MultiFile.slaves) {
										var f = MultiFile.slaves[x];
										if(f!=null && f!=undefined){
											var files = ((f.files&&f.files.length) ? f.files : null) || [{
														name: this.value,
														size: 0,
														type: ((this.value || '').match(/[^\.]+$/i) || [''])[0]
													}];
											// make a normal array
											$.each(files, function (i, file) {
												if(file.name!=undefined)
													newfs[newfs.length] = file;
											});
										};
									};
									MultiFile.files = newfs;

									//# Trigger Event! afterFileRemove
									MultiFile.trigger('afterFileRemove', slave, MultiFile, files);
									//# End Event!

									//# Trigger Event! onFileChange
									MultiFile.trigger('FileChange', slave, MultiFile, MultiFile.files);
									//# End Event!

									return false;
								});

						// Insert label
						MultiFile.list.append(
							r.append(b, ' ', names)
						);

					//}); // each file?

					//# Trigger Event! afterFileAppend
					MultiFile.trigger('afterFileAppend', slave, MultiFile, files);
					//# End Event!

					//# Trigger Event! onFileChange
					MultiFile.trigger('FileChange', slave, MultiFile, MultiFile.files);
					//# End Event!

				}; // MultiFile.addToList
				// Add element to selected files list

				// Bind functionality to the first element
				if (!MultiFile.MultiFile) MultiFile.addSlave(MultiFile.e, 0);

				// Increment control count
				//MultiFile.I++; // using window.MultiFile
				MultiFile.n++;

				// Save control to element
				MultiFile.E.data('MultiFile', MultiFile);

				//#####################################################################
				// MAIN PLUGIN FUNCTIONALITY - END
				//#####################################################################
			}); // each element
	};

**Comment by Ananthan209** [comment]
![untitled](https://cloud.githubusercontent.com/assets/18587821/14698544/f26b9bc8-075d-11e6-9777-abde20f035c0.jpg)

**Comment by fyneworks** [comment]
When the user select multiple files together they can only be removed together.

That cannot be done at this stage by this plugin.
