### ISSUE TITLE
Way to trigger select file

### ISSUE THREAD

**Issue by Decadence** [fyneworks/multifile#50]
Need some way to trigger select file dialog.
For example if you want apply some CSS styles to button that triggers file select, one way is to $(".file").click() while click on it but it will trigger select on all added inputs with the same class.
You can just add some class for current visible input. Now there is no way to identify visible input.
They have different IDs but how to get ID of visible input?

**Comment by Decadence** [comment]
Solution:

Add class on 337 line:
```javascript
newEle.addClass('MultiFile visible_file');
```

and remove it after successful selection:
```javascript
$(this).css({
   position: 'absolute',
   top: '-3000px'
});

$(this).removeClass("visible_file");
```

I think class should be an option.

I can make PR, but it would be faster if you make this changes.

**Comment by Decadence** [comment]
@fyneworks bump

**Comment by ltdeta** [comment]
Can you please implement this in Multifile?
