### ISSUE TITLE
Drag and Drop feature

### ISSUE THREAD

**Issue by jravi** [fyneworks/multifile#6]
Is there any drag drop feature available for this plugin? or any way to integrate with other drag drop plugin?

**Comment by ymycorp** [comment]
Hello! I like this plugin but the drag and drop also missing for me. Is there any way to implement?

**Comment by fyneworks** [comment]
Do you guys mean drag and drop files outside the browser (ie.: from file explorer) into a defined area?  Like this? http://stackoverflow.com/questions/8006715/drag-drop-files-into-standard-html-file-input

**Comment by fyneworks** [comment]
Or this:
http://updates.html5rocks.com/2012/07/Drag-and-drop-a-folder-onto-Chrome-now-available

**Comment by fyneworks** [comment]
Or even better, this: http://stackoverflow.com/questions/2657653/drag-and-drop-file-upload-in-google-chrome-chromium-and-safari
