### ISSUE TITLE
jQuery.MultiFile.min.js not up-to-date

### ISSUE THREAD

**Issue by mirabilos** [fyneworks/multifile#68]
jQuery.MultiFile.min.js was last changed in April 2016, jquery.MultiFile.js in June 2016…

**Comment by fyneworks** [comment]
I'm unable to maintain the project any more but have made you a collaborator. Hope that's OK.

**Comment by fyneworks** [comment]
The min file is compiled manually using https://closure-compiler.appspot.com/home - this project pre-dates  node, I think maybe even github itself, haha.

**Comment by mirabilos** [comment]
OK, thanks, will have a look at it.

**Comment by mirabilos** [comment]
Working on it. I got the docs to build, with some fixes, will need to work on minification (apparently uglifyjs via grunt via npm… *sigh*). But I’m letting you know I’m on it and will release an updated version soon™.

**Comment by mirabilos** [comment]
I fixed the build process, regenerated the file and released v2.2.2 (from whatever code was at the HEAD of the master branch) to fix this issue.
