### ISSUE TITLE
Comma separator option for multi upload preview

### ISSUE THREAD

**Issue by Ralfi18** [fyneworks/multifile#73]
Is it possible to make the comma for preview of multiple images optional. The code is on line 475 
in master branch / if (i > 0) names.append(', ');  /

**Comment by fyneworks** [comment]
Done. Hopefully thsi will do the trick.

```
	$('#your-input').MultiFile({

                // this option will remove the comma 
                // between file names when multiple
                // files are selected at once
                separator: false

	});
```

ps.: either an empty string or "null" or "false" will work, as long as !!separator evaluates to "false".
