### ISSUE TITLE
total_size does not reduce when files removed

### ISSUE THREAD

**Issue by devnuhl** [fyneworks/multifile#8]
If you add files the size increases, but the size never decreases when files are removed. console.log of the passed objects to the events will verify that the size does not change when removing files.

I imagine this might tie in with what was being said in #3 about removing and re-adding files. This has been produced and reproduced in Version 37.0.2062.124 m of Chrome.

**Comment by nehaBohra** [comment]
I am facing the same issue in firefox as well as in chrome.

**Comment by fyneworks** [comment]
Sorry I haven't had time to work on this project for a while! Addressed the issue in v2.2

**Comment by nehaBohra** [comment]
Thank you so much!

On Mon, Mar 23, 2015 at 5:36 PM, Fyneworks <notifications@github.com> wrote:

> Closed #8 <https://github.com/fyneworks/multifile/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fyneworks/multifile/issues/8#event-262233929>.
>



-- 
Regards ,
Neha Bohra
Volansys Technologies Pvt. Ltd.
Ph: +91 79 40041994
Website: www.volansys.com

**Comment by nehaBohra** [comment]
We are using spring in backend and its the only plugin that can be used for
multi upload with a single request.

On Mon, Mar 23, 2015 at 8:11 PM, Neha Bohra <neha.bohra@volansystech.com>
wrote:

> Thank you so much!
>
> On Mon, Mar 23, 2015 at 5:36 PM, Fyneworks <notifications@github.com>
> wrote:
>
>> Closed #8 <https://github.com/fyneworks/multifile/issues/8>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fyneworks/multifile/issues/8#event-262233929>.
>>
>
>
>
> --
> Regards ,
> Neha Bohra
> Volansys Technologies Pvt. Ltd.
> Ph: +91 79 40041994
> Website: www.volansys.com
>



-- 
Regards ,
Neha Bohra
Volansys Technologies Pvt. Ltd.
Ph: +91 79 40041994
Website: www.volansys.com
